Projects/CRUD1/CRUD1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstcrud.urls")),
]

Projects/CRUD1/firstcrud/urls.py
from django.urls import path
from . import views
app_name = 'firstcrud'
urlpatterns = [
    path('', views.home,name="home"),
    path('form/', views.form, name = "form"),
]

Projects/CRUD1/firstcrud/models.py
from django.db import models

# Create your models here.
class testCrud(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    
    def __str__(self):
        return self.name
    

Projects/CRUD1/firstcrud/forms.py
from django import forms
from . import models

class firstCrudForm(forms.ModelForm):
    class Meta:
        model = models.testCrud
        fields = "__all__"
        
        

Projects/CRUD1/firstcrud/views.py
from django.shortcuts import render
from . import forms
from firstcrud.models import *
# Create your views here.
def home(request):
    testcrud = testCrud.objects.all()
    dict ={
        'testCrud' : testcrud,
    }
    return render(request, 'firstcrud/index.html', context = dict)

def form(request):
    firstCrudForm = forms.firstCrudForm
    dict = {
        'firstCrudForm' : firstCrudForm,
    }
    if request.method == "POST":
        firstCrudForm = forms.firstCrudForm(request.POST)
        if firstCrudForm.is_valid():
            firstCrudForm.save(commit=True)
            return home(request)
    return render(request, 'firstcrud/form.html', context=dict)

Projects/CRUD1/templates/firstcrud/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {{ firstCrudForm.as_p }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
    <a href="{% url 'firstcrud:home' %}">Back</a>
</body>
</html>

Projects/CRUD1/templates/firstcrud/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>
                Age
            </th>
        </tr>
        {% for data in testCrud %}
        <tr>
            <td>{{ data.name }}</td>
            <td>{{ data.age }}</td>
        </tr>
        {% endfor %}
        
    </table>
    <a href="{% url 'firstcrud:form' %}">add</a>
</body>
</html>